/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioUnificadoRouteImport } from './routes/relatorio-unificado'
import { Route as ReelsOrganicoRouteImport } from './routes/reels-organico'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as OrganicoInstagramRouteImport } from './routes/organico-instagram'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NegativasRouteImport } from './routes/negativas'
import { Route as GerenciarAnunciosRouteImport } from './routes/gerenciar-anuncios'
import { Route as GeradorCopyRouteImport } from './routes/gerador-copy'
import { Route as DiagnosticoMetaRouteImport } from './routes/diagnostico-meta'
import { Route as DashboardMetaRouteImport } from './routes/dashboard-meta'
import { Route as DashboardGoogleRouteImport } from './routes/dashboard-google'
import { Route as DashboardConteudoRouteImport } from './routes/dashboard-conteudo'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConectarContasRouteImport } from './routes/conectar-contas'
import { Route as CarrosseisRouteImport } from './routes/carrosseis'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuditoriaMetaRouteImport } from './routes/auditoria-meta'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as SkillSkillIdRouteImport } from './routes/skill.$skillId'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as HubHubIdRouteImport } from './routes/hub.$hubId'
import { Route as ApiPublicSiteEditRouteImport } from './routes/api/public/site-edit'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const RelatorioUnificadoRoute = RelatorioUnificadoRouteImport.update({
  id: '/relatorio-unificado',
  path: '/relatorio-unificado',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsOrganicoRoute = ReelsOrganicoRouteImport.update({
  id: '/reels-organico',
  path: '/reels-organico',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganicoInstagramRoute = OrganicoInstagramRouteImport.update({
  id: '/organico-instagram',
  path: '/organico-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NegativasRoute = NegativasRouteImport.update({
  id: '/negativas',
  path: '/negativas',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciarAnunciosRoute = GerenciarAnunciosRouteImport.update({
  id: '/gerenciar-anuncios',
  path: '/gerenciar-anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorCopyRoute = GeradorCopyRouteImport.update({
  id: '/gerador-copy',
  path: '/gerador-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoMetaRoute = DiagnosticoMetaRouteImport.update({
  id: '/diagnostico-meta',
  path: '/diagnostico-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMetaRoute = DashboardMetaRouteImport.update({
  id: '/dashboard-meta',
  path: '/dashboard-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGoogleRoute = DashboardGoogleRouteImport.update({
  id: '/dashboard-google',
  path: '/dashboard-google',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConteudoRoute = DashboardConteudoRouteImport.update({
  id: '/dashboard-conteudo',
  path: '/dashboard-conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarContasRoute = ConectarContasRouteImport.update({
  id: '/conectar-contas',
  path: '/conectar-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosseisRoute = CarrosseisRouteImport.update({
  id: '/carrosseis',
  path: '/carrosseis',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaMetaRoute = AuditoriaMetaRouteImport.update({
  id: '/auditoria-meta',
  path: '/auditoria-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSkillIdRoute = SkillSkillIdRouteImport.update({
  id: '/skill/$skillId',
  path: '/skill/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const HubHubIdRoute = HubHubIdRouteImport.update({
  id: '/hub/$hubId',
  path: '/hub/$hubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteEditRoute = ApiPublicSiteEditRouteImport.update({
  id: '/api/public/site-edit',
  path: '/api/public/site-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria-meta': typeof AuditoriaMetaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carrosseis': typeof CarrosseisRoute
  '/conectar-contas': typeof ConectarContasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/dashboard-conteudo': typeof DashboardConteudoRoute
  '/dashboard-google': typeof DashboardGoogleRoute
  '/dashboard-meta': typeof DashboardMetaRoute
  '/diagnostico-meta': typeof DiagnosticoMetaRoute
  '/gerador-copy': typeof GeradorCopyRoute
  '/gerenciar-anuncios': typeof GerenciarAnunciosRoute
  '/negativas': typeof NegativasRoute
  '/onboarding': typeof OnboardingRoute
  '/organico-instagram': typeof OrganicoInstagramRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/reels': typeof ReelsRoute
  '/reels-organico': typeof ReelsOrganicoRoute
  '/relatorio-unificado': typeof RelatorioUnificadoRoute
  '/hub/$hubId': typeof HubHubIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
  '/sites/': typeof SitesIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/site-edit': typeof ApiPublicSiteEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria-meta': typeof AuditoriaMetaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carrosseis': typeof CarrosseisRoute
  '/conectar-contas': typeof ConectarContasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/dashboard-conteudo': typeof DashboardConteudoRoute
  '/dashboard-google': typeof DashboardGoogleRoute
  '/dashboard-meta': typeof DashboardMetaRoute
  '/diagnostico-meta': typeof DiagnosticoMetaRoute
  '/gerador-copy': typeof GeradorCopyRoute
  '/gerenciar-anuncios': typeof GerenciarAnunciosRoute
  '/negativas': typeof NegativasRoute
  '/onboarding': typeof OnboardingRoute
  '/organico-instagram': typeof OrganicoInstagramRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/reels': typeof ReelsRoute
  '/reels-organico': typeof ReelsOrganicoRoute
  '/relatorio-unificado': typeof RelatorioUnificadoRoute
  '/hub/$hubId': typeof HubHubIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
  '/sites': typeof SitesIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/site-edit': typeof ApiPublicSiteEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria-meta': typeof AuditoriaMetaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carrosseis': typeof CarrosseisRoute
  '/conectar-contas': typeof ConectarContasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/dashboard-conteudo': typeof DashboardConteudoRoute
  '/dashboard-google': typeof DashboardGoogleRoute
  '/dashboard-meta': typeof DashboardMetaRoute
  '/diagnostico-meta': typeof DiagnosticoMetaRoute
  '/gerador-copy': typeof GeradorCopyRoute
  '/gerenciar-anuncios': typeof GerenciarAnunciosRoute
  '/negativas': typeof NegativasRoute
  '/onboarding': typeof OnboardingRoute
  '/organico-instagram': typeof OrganicoInstagramRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/reels': typeof ReelsRoute
  '/reels-organico': typeof ReelsOrganicoRoute
  '/relatorio-unificado': typeof RelatorioUnificadoRoute
  '/hub/$hubId': typeof HubHubIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
  '/sites/': typeof SitesIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/site-edit': typeof ApiPublicSiteEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/auditoria-meta'
    | '/biblioteca'
    | '/carrosseis'
    | '/conectar-contas'
    | '/configuracoes'
    | '/conteudo'
    | '/dashboard-conteudo'
    | '/dashboard-google'
    | '/dashboard-meta'
    | '/diagnostico-meta'
    | '/gerador-copy'
    | '/gerenciar-anuncios'
    | '/negativas'
    | '/onboarding'
    | '/organico-instagram'
    | '/prospeccao'
    | '/reels'
    | '/reels-organico'
    | '/relatorio-unificado'
    | '/hub/$hubId'
    | '/sites/$siteId'
    | '/skill/$skillId'
    | '/sites/'
    | '/api/public/chat'
    | '/api/public/site-edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/auditoria-meta'
    | '/biblioteca'
    | '/carrosseis'
    | '/conectar-contas'
    | '/configuracoes'
    | '/conteudo'
    | '/dashboard-conteudo'
    | '/dashboard-google'
    | '/dashboard-meta'
    | '/diagnostico-meta'
    | '/gerador-copy'
    | '/gerenciar-anuncios'
    | '/negativas'
    | '/onboarding'
    | '/organico-instagram'
    | '/prospeccao'
    | '/reels'
    | '/reels-organico'
    | '/relatorio-unificado'
    | '/hub/$hubId'
    | '/sites/$siteId'
    | '/skill/$skillId'
    | '/sites'
    | '/api/public/chat'
    | '/api/public/site-edit'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/auditoria-meta'
    | '/biblioteca'
    | '/carrosseis'
    | '/conectar-contas'
    | '/configuracoes'
    | '/conteudo'
    | '/dashboard-conteudo'
    | '/dashboard-google'
    | '/dashboard-meta'
    | '/diagnostico-meta'
    | '/gerador-copy'
    | '/gerenciar-anuncios'
    | '/negativas'
    | '/onboarding'
    | '/organico-instagram'
    | '/prospeccao'
    | '/reels'
    | '/reels-organico'
    | '/relatorio-unificado'
    | '/hub/$hubId'
    | '/sites/$siteId'
    | '/skill/$skillId'
    | '/sites/'
    | '/api/public/chat'
    | '/api/public/site-edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  AuditoriaMetaRoute: typeof AuditoriaMetaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CarrosseisRoute: typeof CarrosseisRoute
  ConectarContasRoute: typeof ConectarContasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConteudoRoute: typeof ConteudoRoute
  DashboardConteudoRoute: typeof DashboardConteudoRoute
  DashboardGoogleRoute: typeof DashboardGoogleRoute
  DashboardMetaRoute: typeof DashboardMetaRoute
  DiagnosticoMetaRoute: typeof DiagnosticoMetaRoute
  GeradorCopyRoute: typeof GeradorCopyRoute
  GerenciarAnunciosRoute: typeof GerenciarAnunciosRoute
  NegativasRoute: typeof NegativasRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganicoInstagramRoute: typeof OrganicoInstagramRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  ReelsRoute: typeof ReelsRoute
  ReelsOrganicoRoute: typeof ReelsOrganicoRoute
  RelatorioUnificadoRoute: typeof RelatorioUnificadoRoute
  HubHubIdRoute: typeof HubHubIdRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SkillSkillIdRoute: typeof SkillSkillIdRoute
  SitesIndexRoute: typeof SitesIndexRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicSiteEditRoute: typeof ApiPublicSiteEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio-unificado': {
      id: '/relatorio-unificado'
      path: '/relatorio-unificado'
      fullPath: '/relatorio-unificado'
      preLoaderRoute: typeof RelatorioUnificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels-organico': {
      id: '/reels-organico'
      path: '/reels-organico'
      fullPath: '/reels-organico'
      preLoaderRoute: typeof ReelsOrganicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organico-instagram': {
      id: '/organico-instagram'
      path: '/organico-instagram'
      fullPath: '/organico-instagram'
      preLoaderRoute: typeof OrganicoInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negativas': {
      id: '/negativas'
      path: '/negativas'
      fullPath: '/negativas'
      preLoaderRoute: typeof NegativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciar-anuncios': {
      id: '/gerenciar-anuncios'
      path: '/gerenciar-anuncios'
      fullPath: '/gerenciar-anuncios'
      preLoaderRoute: typeof GerenciarAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-copy': {
      id: '/gerador-copy'
      path: '/gerador-copy'
      fullPath: '/gerador-copy'
      preLoaderRoute: typeof GeradorCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-meta': {
      id: '/diagnostico-meta'
      path: '/diagnostico-meta'
      fullPath: '/diagnostico-meta'
      preLoaderRoute: typeof DiagnosticoMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-meta': {
      id: '/dashboard-meta'
      path: '/dashboard-meta'
      fullPath: '/dashboard-meta'
      preLoaderRoute: typeof DashboardMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-google': {
      id: '/dashboard-google'
      path: '/dashboard-google'
      fullPath: '/dashboard-google'
      preLoaderRoute: typeof DashboardGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-conteudo': {
      id: '/dashboard-conteudo'
      path: '/dashboard-conteudo'
      fullPath: '/dashboard-conteudo'
      preLoaderRoute: typeof DashboardConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar-contas': {
      id: '/conectar-contas'
      path: '/conectar-contas'
      fullPath: '/conectar-contas'
      preLoaderRoute: typeof ConectarContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrosseis': {
      id: '/carrosseis'
      path: '/carrosseis'
      fullPath: '/carrosseis'
      preLoaderRoute: typeof CarrosseisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria-meta': {
      id: '/auditoria-meta'
      path: '/auditoria-meta'
      fullPath: '/auditoria-meta'
      preLoaderRoute: typeof AuditoriaMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$skillId': {
      id: '/skill/$skillId'
      path: '/skill/$skillId'
      fullPath: '/skill/$skillId'
      preLoaderRoute: typeof SkillSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$hubId': {
      id: '/hub/$hubId'
      path: '/hub/$hubId'
      fullPath: '/hub/$hubId'
      preLoaderRoute: typeof HubHubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-edit': {
      id: '/api/public/site-edit'
      path: '/api/public/site-edit'
      fullPath: '/api/public/site-edit'
      preLoaderRoute: typeof ApiPublicSiteEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  AuditoriaMetaRoute: AuditoriaMetaRoute,
  BibliotecaRoute: BibliotecaRoute,
  CarrosseisRoute: CarrosseisRoute,
  ConectarContasRoute: ConectarContasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConteudoRoute: ConteudoRoute,
  DashboardConteudoRoute: DashboardConteudoRoute,
  DashboardGoogleRoute: DashboardGoogleRoute,
  DashboardMetaRoute: DashboardMetaRoute,
  DiagnosticoMetaRoute: DiagnosticoMetaRoute,
  GeradorCopyRoute: GeradorCopyRoute,
  GerenciarAnunciosRoute: GerenciarAnunciosRoute,
  NegativasRoute: NegativasRoute,
  OnboardingRoute: OnboardingRoute,
  OrganicoInstagramRoute: OrganicoInstagramRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  ReelsRoute: ReelsRoute,
  ReelsOrganicoRoute: ReelsOrganicoRoute,
  RelatorioUnificadoRoute: RelatorioUnificadoRoute,
  HubHubIdRoute: HubHubIdRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  SkillSkillIdRoute: SkillSkillIdRoute,
  SitesIndexRoute: SitesIndexRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicSiteEditRoute: ApiPublicSiteEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
